In [1]:
import os

import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings("ignore")

# Load Data

In [3]:
# check shape of data

data_path = "data/Data"

for data in os.listdir(data_path):
    file = os.path.join(data_path, data)
    
    df = pd.read_csv(file)
    print(f"{data} shape: {df.shape}")

fasting.csv shape: (6189, 3)
harvests.csv shape: (8087, 9)
fastings.csv shape: (32379, 3)
mortalities.csv shape: (13221, 7)
samplings.csv shape: (15032, 7)
feeds.csv shape: (706908, 3)
cycles.csv shape: (2617, 24)
ponds.csv shape: (338, 10)
measurements.csv shape: (139050, 24)
farms.csv shape: (551, 4)
feed_tray.csv shape: (186664, 10)

In [4]:
# calculate sparse rate

for data in os.listdir(data_path):
    file = os.path.join(data_path, data)
    
    df = pd.read_csv(file)
    sparse_rate = (df.isna().sum().sum() / df.size) * 100
    print(f"{data} sparse rate: {sparse_rate:.2f} %")

fasting.csv sparse rate: 0.09 %
harvests.csv sparse rate: 2.82 %
fastings.csv sparse rate: 0.04 %
mortalities.csv sparse rate: 0.00 %
samplings.csv sparse rate: 13.01 %
feeds.csv sparse rate: 0.00 %
cycles.csv sparse rate: 7.93 %
ponds.csv sparse rate: 10.27 %
measurements.csv sparse rate: 62.54 %
farms.csv sparse rate: 7.49 %
feed_tray.csv sparse rate: 7.52 %

In [5]:
# see columns

for data in os.listdir(data_path):
    file = os.path.join(data_path, data)
    
    df = pd.read_csv(file)
    print(f"{data} columns: {df.columns}")

fasting.csv columns: Index(['logged_date', 'cycle_id', 'fasting'], dtype='object')
harvests.csv columns: Index(['cycle_id', 'updated_at', 'size', 'created_at', 'weight', 'id',
       'harvested_at', 'status', 'selling_price'],
      dtype='object')
fastings.csv columns: Index(['logged_date', 'cycle_id', 'fasting'], dtype='object')
mortalities.csv columns: Index(['id', 'cycle_id', 'quantity', 'recorded_at', 'created_at', 'updated_at',
       'average_weight'],
      dtype='object')
samplings.csv columns: Index(['cycle_id', 'updated_at', 'sampled_at', 'created_at', 'average_weight',
       'id', 'remark'],
      dtype='object')
feeds.csv columns: Index(['cycle_id', 'logged_at', 'quantity'], dtype='object')
cycles.csv columns: Index(['id', 'pond_id', 'species_id', 'total_seed', 'started_at',
       'finished_at', 'remark', 'created_at', 'updated_at', 'area',
       'initial_age', 'limit_weight_per_area', 'target_cultivation_day',
       'target_size', 'extracted_at', 'subscription_type', 'ordered_at',
       'hatchery_id', 'total_seed_type', 'hatchery_name', 'pond_name',
       'pond_length', 'pond_width', 'pond_depth'],
      dtype='object')
ponds.csv columns: Index(['id', 'farm_id', 'length', 'width', 'deep', 'created_at', 'updated_at',
       'record_id', 'extracted_at', 'max_seed_density'],
      dtype='object')
measurements.csv columns: Index(['pond_id', 'cycle_id', 'measured_date', 'morning_temperature',
       'evening_temperature', 'morning_do', 'evening_do', 'morning_salinity',
       'evening_salinity', 'morning_pH', 'evening_pH', 'transparency',
       'turbidity', 'ammonia', 'nitrate', 'nitrite', 'alkalinity', 'hardness',
       'calcium', 'magnesium', 'carbonate', 'bicarbonate', 'tom',
       'total_plankton_'],
      dtype='object')
farms.csv columns: Index(['id', 'province', 'regency', 'timezone'], dtype='object')
feed_tray.csv columns: Index(['id', 'logged_at', 'feed_logged_at', 'cycle_id', 'tray_number',
       'feed_remaining_percent', 'remark', 'created_at', 'updated_at',
       'local_feed_logged_at'],
      dtype='object')

## fasting or fastings?

In [6]:
# analyze fasting.csv and fastings.csv

fasting_file = os.path.join(data_path, "fastings.csv")
fasting_df = pd.read_csv(fasting_file)

fastings_file = os.path.join(data_path, "fasting.csv")
fastings_df = pd.read_csv(fastings_file)

display(fastings_df.head(10))
display(fasting_df.head(10))

  logged_date  cycle_id  fasting
0  2022-10-17     15804      1.0
1  2022-11-27     15804      0.0
2  2022-11-28     15804      0.0
3  2022-11-29     15804      0.0
4  2022-12-01     15804      1.0
5  2021-05-20     16250      1.0
6  2022-08-16     15487      0.0
7  2022-03-28     15106      1.0
8  2022-04-10     15106      1.0
9  2022-04-18     15106      1.0

  logged_date  cycle_id  fasting
0  2022-03-26   15013.0      1.0
1  2022-03-27   15013.0      0.0
2  2022-03-28   15013.0      0.0
3  2022-04-10   15013.0      1.0
4  2021-10-23   11848.0      1.0
5  2021-10-22   11848.0      1.0
6  2021-09-22   11848.0      1.0
7  2021-09-21   11848.0      1.0
8  2021-09-20   11848.0      1.0
9  2021-09-19   11848.0      1.0

In [7]:
# see one of the cycle id sample

display(fastings_df[fastings_df["cycle_id"] == 15804])
display(fasting_df[fasting_df["cycle_id"] == 15804])

  logged_date  cycle_id  fasting
0  2022-10-17     15804      1.0
1  2022-11-27     15804      0.0
2  2022-11-28     15804      0.0
3  2022-11-29     15804      0.0
4  2022-12-01     15804      1.0

      logged_date  cycle_id  fasting
26143  2022-07-24   15804.0      0.0
26144  2022-07-21   15804.0      0.0
26145  2022-07-22   15804.0      0.0
26146  2022-07-23   15804.0      0.0
26147  2022-07-20   15804.0      0.0
26148  2022-07-19   15804.0      0.0
26149  2022-07-18   15804.0      0.0
26150  2022-07-17   15804.0      0.0
26151  2022-07-16   15804.0      0.0
26152  2022-07-15   15804.0      0.0
26153  2022-07-25   15804.0      0.0
26154  2022-05-29   15804.0      1.0
26155  2022-05-30   15804.0      1.0
26156  2022-05-31   15804.0      1.0
26157  2022-06-01   15804.0      1.0
26158  2022-06-02   15804.0      1.0
26159  2022-06-03   15804.0      1.0
26160  2022-06-04   15804.0      1.0
26161  2022-06-05   15804.0      1.0
26162  2022-07-26   15804.0      1.0
26163  2022-07-27   15804.0      1.0

## Data Cleaning

In [8]:
os.listdir(data_path)

['fasting.csv',
 'harvests.csv',
 'fastings.csv',
 'mortalities.csv',
 'samplings.csv',
 'feeds.csv',
 'cycles.csv',
 'ponds.csv',
 'measurements.csv',
 'farms.csv',
 'feed_tray.csv']

In [9]:
df_cycles = pd.read_csv("data/Data/cycles.csv")
df_fastings = pd.read_csv("data/Data/fastings.csv")
df_fasting = pd.read_csv("data/Data/fasting.csv")
df_feed_trays = pd.read_csv("data/Data/feed_tray.csv")
df_feeds = pd.read_csv("data/Data/feeds.csv")
df_harvest = pd.read_csv("data/Data/harvests.csv")
df_measurements = pd.read_csv("data/Data/measurements.csv")
df_mortalities = pd.read_csv("data/Data/mortalities.csv")
df_samplings = pd.read_csv("data/Data/samplings.csv")

In [10]:
# remove columns didn't exists in test document

drop_harvests_columns = ["updated_at", "created_at", "id"]
drop_mortalities_columns = ["updated_at", "created_at", "id"]
drop_samplings_columns = ["updated_at", "created_at", "id", "remark"]
drop_cycles_columns = [
    'remark', 
    'created_at', 
    'updated_at', 
    'initial_age', 
    'limit_weight_per_area', 
    'target_cultivation_day',
    'target_size', 
    'extracted_at', 
    'subscription_type', 
    'ordered_at',
    'hatchery_id', 
    'total_seed_type', 
    'hatchery_name', 
    'pond_name',
    'species_id'
]
drop_measurements_columns = ['pond_id', 'turbidity']
drop_feed_trays_columns = ["id", "created_at", "updated_at", 'local_feed_logged_at']

In [11]:
# rename id in cycle_id for easier merge
df_cycles = df_cycles.rename(columns={"id": "cycle_id"})

# drop unnecessary columns
df_harvest = df_harvest.drop(columns=drop_harvests_columns)
df_mortalities = df_mortalities.drop(columns=drop_mortalities_columns)
df_samplings = df_samplings.drop(columns=drop_samplings_columns)
df_cycles = df_cycles.drop(columns=drop_cycles_columns)
df_measurements = df_measurements.drop(columns=drop_measurements_columns)
df_feed_trays = df_feed_trays.drop(columns=drop_feed_trays_columns)

# join two fasting dataframes
df_fasting = pd.concat([df_fasting, df_fastings],axis=0)

In [12]:
list_df = {
    "df_cycles": df_cycles,
    "df_fasting": df_fasting,
    "df_feed_trays": df_feed_trays,
    "df_feeds": df_feeds,
    "df_harvest": df_harvest,
    "df_measurements": df_measurements,
    "df_mortalities": df_mortalities,
    "df_samplings": df_samplings
}

In [13]:
# check for duplicates

for name, df in list_df.items():
    print(f"{name} num_duplicate: {df.duplicated().sum()}")

df_cycles num_duplicate: 117
df_fasting num_duplicate: 460
df_feed_trays num_duplicate: 5208
df_feeds num_duplicate: 154995
df_harvest num_duplicate: 107
df_measurements num_duplicate: 0
df_mortalities num_duplicate: 24
df_samplings num_duplicate: 292

In [14]:
# drop duplicates in dataframe

for name, df in list_df.items():
    list_df[name] = df.drop_duplicates()

## Identify Missing Value and Inconsistent Data

In [15]:
for name, df in list_df.items():

    nan = [float(df[col].isna().sum() * 100 / df.shape[0]) for col in df.columns]
    unique = [df[col].nunique() for col in df.columns]
    dtype = [df[col].dtype for col in df.columns]

    print(name)
    display(pd.DataFrame({
        "name": df.columns, 
        "dtype": dtype, 
        "n_unique": unique, 
        "% NaN": nan
    }))

df_cycles

          name    dtype  n_unique  % NaN
0     cycle_id    int64      2500   0.00
1      pond_id    int64      1675   0.00
2   total_seed    int64       868   0.00
3   started_at   object       750   0.00
4  finished_at   object       857   0.04
5         area  float64       648   0.00
6  pond_length  float64       339   0.24
7   pond_width  float64       384   0.24
8   pond_depth  float64        37   4.72

df_fasting

          name    dtype  n_unique     % NaN
0  logged_date   object      1154  0.000000
1     cycle_id  float64      1797  0.000000
2      fasting  float64         2  0.144327

df_feed_trays

                     name   dtype  n_unique      % NaN
0               logged_at  object     16592   0.000000
1          feed_logged_at  object     15298   0.000000
2                cycle_id   int64       709   0.000000
3             tray_number   int64         6   0.000000
4  feed_remaining_percent   int64         3   0.000000
5                  remark  object       739  74.837977

df_feeds

        name    dtype  n_unique    % NaN
0   cycle_id    int64      2500  0.00000
1  logged_at   object     74841  0.00308
2   quantity  float64      6404  0.00308

df_harvest

            name    dtype  n_unique      % NaN
0       cycle_id  float64      2490   0.000000
1           size  float64      1481   0.000000
2         weight  float64      5109   0.000000
3   harvested_at   object      1069   0.000000
4         status   object        13   3.233083
5  selling_price  float64      4981  22.243108

df_measurements

                   name    dtype  n_unique      % NaN
0              cycle_id    int64      2500   0.000000
1         measured_date   object      1427   0.000000
2   morning_temperature  float64      4793  30.100683
3   evening_temperature  float64      5386  35.842503
4            morning_do  float64      6531  44.102122
5            evening_do  float64      7706  46.816253
6      morning_salinity  float64     19113  33.360662
7      evening_salinity  float64     18407  53.187343
8            morning_pH  float64      3190  14.466019
9            evening_pH  float64      2417  56.167566
10         transparency  float64       527  44.408486
11              ammonia  float64       291  97.304567
12              nitrate  float64       104  98.445164
13              nitrite  float64       993  92.983100
14           alkalinity  float64       523  90.279036
15             hardness  float64      1225  96.026609
16              calcium  float64       472  95.259259
17            magnesium  float64      1139  95.239123
18            carbonate  float64       107  96.197051
19          bicarbonate  float64       354  95.197411
20                  tom  float64      1270  94.767350
21      total_plankton_  float64      2605  90.923409

df_mortalities

             name    dtype  n_unique  % NaN
0        cycle_id    int64       857    0.0
1        quantity    int64      2538    0.0
2     recorded_at   object       896    0.0
3  average_weight  float64      1984    0.0

df_samplings

             name    dtype  n_unique  % NaN
0        cycle_id  float64      2307    0.0
1      sampled_at   object      1221    0.0
2  average_weight  float64      2666    0.0

In [16]:
# convert cycle_id to int

for name, df in list_df.items():
    df["cycle_id"] = df["cycle_id"].astype("int64")

In [17]:
# check date consistency

for name, df in list_df.items():
    date_col = df.filter(regex=r'.*(_at|_date)$').columns
    for col in date_col:
        invalid_dates = df[~df[col].str.len().isin([10, 19])]
        print(f"{name} -> {col} : ")
        display(invalid_dates)

df_cycles -> started_at :

,cycle_id,pond_id,total_seed,started_at,finished_at,area,pond_length,pond_width,pond_depth
0,18876,36294,331920,2022-10-14 00:00:00.000,2023-01-29 00:00:00.000,4030.0,65.00,62.00,1.0
1,22118,37102,40000,2023-04-26 00:00:00.000,2023-06-23 00:00:00.000,399.0,30.00,20.00,1.0
2,24088,39154,357570,2023-08-01 00:00:00.000,2023-10-18 00:00:00.000,2000.0,50.00,40.00,1.4
3,17743,20914,168275,2022-07-19 00:00:00.000,2022-09-29 00:00:00.000,1512.0,54.00,28.00,1.5
4,17125,34187,188000,2022-07-07 00:00:00.000,2022-09-20 00:00:00.000,1225.0,35.00,35.00,1.2
...,...,...,...,...,...,...,...,...,...
2612,19131,34712,300000,2022-10-25 00:00:00.000,2023-01-21 00:00:00.000,4999.9,70.71,70.71,1.5
2613,27552,45697,100000,2023-11-05 00:00:00.000,2024-02-13 00:00:00.000,900.0,45.00,20.00,1.5
2614,27885,24570,30716,2023-12-02 00:00:00.000,2024-02-29 00:00:00.000,86.0,10.71,8.03,1.0
2615,15868,32398,150000,2022-04-28 00:00:00.000,2022-06-21 00:00:00.000,1600.0,45.00,35.00,2.0
2616,20849,35913,384000,2023-02-09 00:00:00.000,2023-04-07 00:00:00.000,2915.0,55.00,53.00,1.7

df_cycles -> finished_at :

,cycle_id,pond_id,total_seed,started_at,finished_at,area,pond_length,pond_width,pond_depth
0,18876,36294,331920,2022-10-14 00:00:00.000,2023-01-29 00:00:00.000,4030.0,65.00,62.00,1.0
1,22118,37102,40000,2023-04-26 00:00:00.000,2023-06-23 00:00:00.000,399.0,30.00,20.00,1.0
2,24088,39154,357570,2023-08-01 00:00:00.000,2023-10-18 00:00:00.000,2000.0,50.00,40.00,1.4
3,17743,20914,168275,2022-07-19 00:00:00.000,2022-09-29 00:00:00.000,1512.0,54.00,28.00,1.5
4,17125,34187,188000,2022-07-07 00:00:00.000,2022-09-20 00:00:00.000,1225.0,35.00,35.00,1.2
...,...,...,...,...,...,...,...,...,...
2612,19131,34712,300000,2022-10-25 00:00:00.000,2023-01-21 00:00:00.000,4999.9,70.71,70.71,1.5
2613,27552,45697,100000,2023-11-05 00:00:00.000,2024-02-13 00:00:00.000,900.0,45.00,20.00,1.5
2614,27885,24570,30716,2023-12-02 00:00:00.000,2024-02-29 00:00:00.000,86.0,10.71,8.03,1.0
2615,15868,32398,150000,2022-04-28 00:00:00.000,2022-06-21 00:00:00.000,1600.0,45.00,35.00,2.0
2616,20849,35913,384000,2023-02-09 00:00:00.000,2023-04-07 00:00:00.000,2915.0,55.00,53.00,1.7

df_fasting -> logged_date :

Empty DataFrame
Columns: [logged_date, cycle_id, fasting]
Index: []

df_feed_trays -> logged_at :

Empty DataFrame
Columns: [logged_at, feed_logged_at, cycle_id, tray_number, feed_remaining_percent, remark]
Index: []

df_feed_trays -> feed_logged_at :

Empty DataFrame
Columns: [logged_at, feed_logged_at, cycle_id, tray_number, feed_remaining_percent, remark]
Index: []

df_feeds -> logged_at :

        cycle_id                logged_at  quantity
0          15013  2022-03-29 00:00:00.000       0.5
1          15013  2022-03-29 05:30:00.000       0.5
2          15013  2022-03-29 11:30:00.000       0.5
3          15013  2022-03-29 14:30:00.000       0.5
4          15013  2022-03-30 00:00:00.000       0.5
...          ...                      ...       ...
706903     24650  2023-09-15 21:47:00.000      10.0
706904     24650  2023-09-19 00:00:00.000      13.2
706905     24650  2023-09-20 00:00:00.000      14.0
706906     24650  2023-09-21 13:54:00.000      10.0
706907     24650  2023-09-22 00:47:00.000      14.0

[551913 rows x 3 columns]

df_harvest -> harvested_at :

Empty DataFrame
Columns: [cycle_id, size, weight, harvested_at, status, selling_price]
Index: []

df_measurements -> measured_date :

Empty DataFrame
Columns: [cycle_id, measured_date, morning_temperature, evening_temperature, morning_do, evening_do, morning_salinity, evening_salinity, morning_pH, evening_pH, transparency, ammonia, nitrate, nitrite, alkalinity, hardness, calcium, magnesium, carbonate, bicarbonate, tom, total_plankton_]
Index: []

[0 rows x 22 columns]

df_mortalities -> recorded_at :

Empty DataFrame
Columns: [cycle_id, quantity, recorded_at, average_weight]
Index: []

df_samplings -> sampled_at :

       cycle_id sampled_at  average_weight
12678     25134    1-01-01            5.72

In [18]:
# remove inconsistency date
list_df["df_samplings"] = list_df["df_samplings"][list_df["df_samplings"]["sampled_at"] != "1-01-01"]

# check inconsistency in df_samplings
display(list_df["df_samplings"][list_df["df_samplings"]["cycle_id"] == 25134])

       cycle_id  sampled_at  average_weight
12676     25134  2023-09-27            2.40
12677     25134  2023-10-04            4.19
12679     25134  2023-10-11            5.72
12680     25134  2023-10-18            8.61
12681     25134  2023-10-25           11.06
12682     25134  2023-10-31           13.33
12683     25134  2023-11-11           17.62
12684     25134  2023-11-06           15.30

In [19]:
# extract date only from dataframe

for name, df in list_df.items():
    date_col = df.filter(regex=r'.*(_at|_date)$').columns
    for col in date_col:
        df[col] = pd.to_datetime(df[col])
    list_df[name] = df

In [20]:
for name, df in list_df.items():
    display(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 2500 entries, 0 to 2616
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cycle_id     2500 non-null   int64
 1   pond_id      2500 non-null   int64
 2   total_seed   2500 non-null   int64
 3   started_at   2500 non-null   datetime64[ns]
 4   finished_at  2499 non-null   datetime64[ns]
 5   area         2500 non-null   float64
 6   pond_length  2494 non-null   float64
 7   pond_width   2494 non-null   float64
 8   pond_depth   2382 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(3)
memory usage: 195.3 KB

None

<class 'pandas.core.frame.DataFrame'>
Index: 38108 entries, 0 to 32378
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   logged_date  38108 non-null  datetime64[ns]
 1   cycle_id     38108 non-null  int64
 2   fasting      38053 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 1.2 MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 181456 entries, 0 to 186663
Data columns (total 6 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   logged_at               181456 non-null  datetime64[ns]
 1   feed_logged_at          181456 non-null  datetime64[ns]
 2   cycle_id                181456 non-null  int64
 3   tray_number             181456 non-null  int64
 4   feed_remaining_percent  181456 non-null  int64
 5   remark                  45658 non-null   object
dtypes: datetime64[ns](2), int64(3), object(1)
memory usage: 9.7+ MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 551913 entries, 0 to 706907
Data columns (total 3 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   cycle_id   551913 non-null  int64
 1   logged_at  551896 non-null  datetime64[ns]
 2   quantity   551896 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 16.8 MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 7980 entries, 0 to 8086
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cycle_id       7980 non-null   int64
 1   size           7980 non-null   float64
 2   weight         7980 non-null   float64
 3   harvested_at   7980 non-null   datetime64[ns]
 4   status         7722 non-null   object
 5   selling_price  6205 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 436.4+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139050 entries, 0 to 139049
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   cycle_id             139050 non-null  int64
 1   measured_date        139050 non-null  datetime64[ns]
 2   morning_temperature  97195 non-null   float64
 3   evening_temperature  89211 non-null   float64
 4   morning_do           77726 non-null   float64
 5   evening_do           73952 non-null   float64
 6   morning_salinity     92662 non-null   float64
 7   evening_salinity     65093 non-null   float64
 8   morning_pH           118935 non-null  float64
 9   evening_pH           60949 non-null   float64
 10  transparency         77300 non-null   float64
 11  ammonia              3748 non-null    float64
 12  nitrate              2162 non-null    float64
 13  nitrite              9757 non-null    float64
 14  alkalinity           13517 non-null   float64
 15  hardness             5525 non-null    float64
 16  calcium              6592 non-null    float64
 17  magnesium            6620 non-null    float64
 18  carbonate            5288 non-null    float64
 19  bicarbonate          6678 non-null    float64
 20  tom                  7276 non-null    float64
 21  total_plankton_      12621 non-null   float64
dtypes: datetime64[ns](1), float64(20), int64(1)
memory usage: 23.3 MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 13197 entries, 0 to 13220
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cycle_id        13197 non-null  int64
 1   quantity        13197 non-null  int64
 2   recorded_at     13197 non-null  datetime64[ns]
 3   average_weight  13197 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2)
memory usage: 515.5 KB

None

<class 'pandas.core.frame.DataFrame'>
Index: 14739 entries, 0 to 15031
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cycle_id        14739 non-null  int64
 1   sampled_at      14739 non-null  datetime64[ns]
 2   average_weight  14739 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 460.6 KB

None

# EDA

## Data Description

In [21]:
# check dataframe shape

for name, df in list_df.items():
    print(f"{name} shape: {df.shape}")

df_cycles shape: (2500, 9)
df_fasting shape: (38108, 3)
df_feed_trays shape: (181456, 6)
df_feeds shape: (551913, 3)
df_harvest shape: (7980, 6)
df_measurements shape: (139050, 22)
df_mortalities shape: (13197, 4)
df_samplings shape: (14739, 3)

In [22]:
# check unique of cycle id

for name, df in list_df.items():
    print(f"{name} cycle_id unique: {df['cycle_id'].nunique()}")

df_cycles cycle_id unique: 2500
df_fasting cycle_id unique: 1797
df_feed_trays cycle_id unique: 709
df_feeds cycle_id unique: 2500
df_harvest cycle_id unique: 2490
df_measurements cycle_id unique: 2500
df_mortalities cycle_id unique: 857
df_samplings cycle_id unique: 2307

In [23]:
# check if cycle id is only unique on df_cycle

id = set(df_cycles["cycle_id"].unique())

for name, df in list_df.items():
    if name == "df_cycles":
        continue
    else:
        cycle_id = set(df["cycle_id"].unique())
        print(f"{name} cycle_id unique: {cycle_id - id}")

df_fasting cycle_id unique: {np.int64(19048), np.int64(15068), np.int64(22404), np.int64(18653)}
df_feed_trays cycle_id unique: set()
df_feeds cycle_id unique: set()
df_harvest cycle_id unique: set()
df_measurements cycle_id unique: set()
df_mortalities cycle_id unique: set()
df_samplings cycle_id unique: set()

In [24]:
# remove cycle id not in df_cycles

df_fasting = df_fasting[~df_fasting["cycle_id"].isin([19048.0, 15068.0, 22404.0, 18653.0])]

## Descriptive statistics

In [26]:
for name, df in list_df.items():
    print(name)
    display(df.describe())
    # display(df.describe(include="object"))

df_cycles

,cycle_id,pond_id,total_seed,started_at,finished_at,area,pond_length,pond_width,pond_depth
count,2500.000000,2500.000000,2.500000e+03,2500,2499,2500.000000,2494.000000,2494.000000,2382.000000
mean,19703.420000,32031.209200,2.171546e+05,2022-10-27 02:43:00.479999744,2023-01-13 17:38:32.124849920,2233.092964,43.480714,35.444254,4.345688
min,3458.000000,1.000000,1.000000e+01,2020-03-07 00:00:00,2020-05-20 00:00:00,1.020000,3.000000,1.500000,0.600000
25%,16038.750000,24265.750000,9.000000e+04,2022-05-08 00:00:00,2022-07-16 12:00:00,803.840000,30.000000,26.000000,1.000000
50%,19778.500000,34492.000000,1.847220e+05,2022-11-16 00:00:00,2023-02-10 00:00:00,1368.000000,40.000000,34.000000,1.250000
75%,24772.250000,39071.000000,3.000000e+05,2023-08-05 00:00:00,2023-10-26 00:00:00,2238.682500,51.640000,43.020000,1.500000
max,29874.000000,47282.000000,1.800000e+06,2024-02-18 00:00:00,2024-04-02 00:00:00,422500.000000,650.000000,650.000000,300.000000
std,6052.327634,10328.825505,1.706622e+05,NaN,NaN,12372.846032,26.284228,22.760681,20.113820

df_fasting

                         logged_date      cycle_id       fasting
count                          38108  38108.000000  38053.000000
mean   2023-01-03 03:54:19.158181888  19803.636087      0.263159
min              2018-06-08 00:00:00   4036.000000      0.000000
25%              2022-08-28 00:00:00  17112.000000      0.000000
50%              2022-11-17 00:00:00  18760.000000      0.000000
75%              2023-07-10 00:00:00  23127.000000      1.000000
max              2024-03-31 00:00:00  29659.000000      1.000000
std                              NaN   4467.631807      0.440354

df_feed_trays

,logged_at,feed_logged_at,cycle_id,tray_number,feed_remaining_percent
count,181456,181456,181456.000000,181456.000000,181456.000000
mean,2023-02-04 17:01:35.046733056,2023-02-04 16:23:23.646785280,20175.558978,1.940118,10.169738
min,2000-01-17 00:00:00,2000-01-06 17:00:00,12163.000000,1.000000,0.000000
25%,2022-07-10 08:30:00,2022-07-10 11:15:00,16164.000000,1.000000,0.000000
50%,2023-01-01 11:30:00,2023-01-01 11:00:13,19313.000000,2.000000,0.000000
75%,2023-09-11 01:00:00,2023-09-10 23:30:00,24087.000000,3.000000,0.000000
max,2024-04-01 12:30:00,2024-04-01 11:30:00,29874.000000,6.000000,66.000000
std,NaN,NaN,4152.257910,1.075024,19.604611

df_feeds

            cycle_id                      logged_at       quantity
count  551913.000000                         551896  551896.000000
mean    20580.525356  2023-02-09 20:07:46.486912256      14.820250
min      3458.000000            2000-01-01 08:00:00      -1.000000
25%     17364.000000            2022-08-23 05:30:00       3.400000
50%     20739.000000            2023-03-23 11:30:00       8.000000
75%     24883.000000            2023-10-07 08:00:00      17.600000
max     29874.000000            2024-04-02 00:00:00    2011.000000
std      5352.885943                            NaN      23.166034

df_harvest

,cycle_id,size,weight,harvested_at,selling_price
count,7980.000000,7980.00000,7980.000000,7980,6.205000e+03
mean,19833.593358,113.55712,780.017744,2023-01-26 05:00:16.240601344,3.171188e+07
min,3458.000000,10.00000,0.000000,2008-05-08 00:00:00,0.000000e+00
25%,16338.750000,60.00000,50.000000,2022-08-03 00:00:00,3.000000e+05
50%,19671.000000,86.00000,250.000000,2023-02-17 00:00:00,6.385600e+06
75%,24694.000000,125.00000,675.225000,2023-10-23 00:00:00,2.600000e+07
max,29874.000000,20000.00000,250000.000000,2024-04-02 00:00:00,1.125000e+10
std,5783.779482,383.58861,4293.349612,NaN,1.652777e+08

df_measurements

,cycle_id,measured_date,morning_temperature,evening_temperature,morning_do,evening_do,morning_salinity,evening_salinity,morning_pH,evening_pH,...,nitrate,nitrite,alkalinity,hardness,calcium,magnesium,carbonate,bicarbonate,tom,total_plankton_
count,139050.00000,139050,97195.000000,89211.000000,77726.000000,73952.000000,92662.000000,65093.000000,118935.000000,60949.000000,...,2162.000000,9757.000000,13517.000000,5.525000e+03,6592.000000,6620.000000,5288.000000,6678.000000,7276.000000,1.262100e+04
mean,20268.85329,2023-01-18 06:39:09.048543488,28.580945,29.908567,5.904100,6.005278,22.777202,22.090321,8.006981,8.212628,...,14.714262,16.400004,124.674397,5.074470e+03,576.667025,1959.711167,12.632430,136.527253,147.341025,5.464905e+05
min,3458.00000,2020-05-03 00:00:00,0.000000,0.000000,-52.885000,-62.837000,-25.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,-15.170000,0.000000e+00
25%,16776.00000,2022-07-22 00:00:00,27.000000,28.900000,4.231000,4.831000,16.800000,15.688000,7.615000,7.900000,...,1.000000,0.019000,100.000000,3.800000e+03,320.000000,930.000000,0.000000,104.000000,64.927500,3.000000e+00
50%,20197.00000,2023-02-10 00:00:00,28.000000,30.000000,4.970000,5.640000,23.000000,21.400000,7.900000,8.200000,...,5.000000,0.060000,125.300000,5.050000e+03,421.000000,1200.000000,0.000000,125.000000,87.585000,2.000000e+05
75%,24739.00000,2023-09-24 00:00:00,29.000000,31.000000,5.640000,6.500000,29.000000,26.950000,8.120000,8.412000,...,20.000000,0.432000,154.000000,5.757000e+03,800.000000,2850.000000,12.000000,152.000000,106.000000,6.900000e+05
max,29874.00000,2024-04-01 00:00:00,27341.000000,1078.933333,60043.000000,6706.000000,15734.000000,33958.000000,7421.000000,862.000000,...,1272.000000,48031.000000,19589.000000,2.000000e+06,11250.000000,32000.000000,2400.000000,19589.000000,73312.000000,2.125053e+08
std,5401.43651,NaN,106.896789,5.817013,216.810423,30.444501,60.788610,152.692575,22.025251,5.094369,...,33.204082,655.855878,182.072375,2.693992e+04,410.013047,1769.190137,89.049388,245.061763,1655.003075,2.228631e+06

df_mortalities

,cycle_id,quantity,recorded_at,average_weight
count,13197.000000,1.319700e+04,13197,13197.000000
mean,20849.183905,1.832937e+03,2023-03-24 21:48:17.840418048,9.619707
min,7273.000000,1.000000e+00,2021-01-22 00:00:00,0.000000
25%,17726.000000,6.000000e+01,2022-09-24 00:00:00,4.550000
50%,19676.000000,2.000000e+02,2023-02-16 00:00:00,7.920000
75%,24092.000000,7.530000e+02,2023-10-11 00:00:00,13.040000
max,29579.000000,1.000000e+07,2024-04-02 00:00:00,1428.570000
std,4100.123189,8.728905e+04,NaN,17.210634

df_samplings

           cycle_id                     sampled_at  average_weight
count  14739.000000                          14739    14739.000000
mean   19984.063709  2023-01-20 15:29:01.746386944        9.887562
min     3458.000000            2020-01-26 00:00:00        0.010000
25%    16624.000000            2022-08-01 00:00:00        4.490000
50%    20408.000000            2023-03-01 00:00:00        8.100000
75%    24692.000000            2023-10-09 00:00:00       13.700000
max    29874.000000            2024-04-10 00:00:00      100.000000
std     5769.921750                            NaN        7.188234

# Feature Engineering

## calculate average body weight

In [27]:
# sort df_samplings by id and sampled_at
list_df["df_samplings"] = list_df["df_samplings"].sort_values(by=["cycle_id", "sampled_at"])

# calculate average body weight
# list_df["df_samplings"]["weight_diff"] = list_df["df_samplings"].groupby("cycle_id")["average_weight"].diff()

list_df["df_samplings"]

      cycle_id sampled_at  average_weight
8745      3458 2020-04-10            4.37
8746      3458 2020-04-17            5.23
8744      3458 2020-04-24            6.69
8743      3458 2020-05-01            8.21
8747      3458 2020-05-08            9.68
...        ...        ...             ...
5770     29874 2024-02-20            4.10
5771     29874 2024-02-27            6.20
5772     29874 2024-03-05            8.39
5773     29874 2024-03-12            8.98
5774     29874 2024-03-19           14.10

[14739 rows x 3 columns]

In [28]:
df_ = list_df["df_samplings"].groupby("cycle_id").filter(lambda x: len(x) > 1)
df_["cycle_id"].nunique()

1907

In [29]:
df_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14339 entries, 8745 to 5774
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cycle_id        14339 non-null  int64
 1   sampled_at      14339 non-null  datetime64[ns]
 2   average_weight  14339 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 448.1 KB

In [32]:
df_

      cycle_id sampled_at  average_weight
8745      3458 2020-04-10            4.37
8746      3458 2020-04-17            5.23
8744      3458 2020-04-24            6.69
8743      3458 2020-05-01            8.21
8747      3458 2020-05-08            9.68
...        ...        ...             ...
5770     29874 2024-02-20            4.10
5771     29874 2024-02-27            6.20
5772     29874 2024-03-05            8.39
5773     29874 2024-03-12            8.98
5774     29874 2024-03-19           14.10

[14339 rows x 3 columns]

# Calculate Key Metrics

## Survival Rate

In [ ]:
# get total shrimps
list_df["df_harvest"]["num_shrimps"] = list_df["df_harvest"]["size"] * list_df["df_harvest"]["weight"]

# merge
list_df["df_cycles"] = pd.merge(list_df["df_cycles"], list_df["df_harvest"].groupby("cycle_id")["num_shrimps"].sum(), how="left", on="cycle_id")

# calculate survival rate
list_df["df_cycles"]["survival_rate"] = list_df["df_cycles"]["num_shrimps"] / list_df["df_cycles"]["total_seed"]

list_df["df_cycles"]

,cycle_id,pond_id,total_seed,started_at,finished_at,area,pond_length,pond_width,pond_depth,num_shrimps,survival_rate
0,18876,36294,331920,2022-10-14,2023-01-29,4030.0,65.00,62.00,1.0,155846.5000,0.469530
1,22118,37102,40000,2023-04-26,2023-06-23,399.0,30.00,20.00,1.0,29700.0000,0.742500
2,24088,39154,357570,2023-08-01,2023-10-18,2000.0,50.00,40.00,1.4,186630.0094,0.521940
3,17743,20914,168275,2022-07-19,2022-09-29,1512.0,54.00,28.00,1.5,117729.4826,0.699626
4,17125,34187,188000,2022-07-07,2022-09-20,1225.0,35.00,35.00,1.2,27930.0000,0.148564
...,...,...,...,...,...,...,...,...,...,...,...
2495,19131,34712,300000,2022-10-25,2023-01-21,4999.9,70.71,70.71,1.5,95312.0000,0.317707
2496,27552,45697,100000,2023-11-05,2024-02-13,900.0,45.00,20.00,1.5,84247.0400,0.842470
2497,27885,24570,30716,2023-12-02,2024-02-29,86.0,10.71,8.03,1.0,29245.7000,0.952132
2498,15868,32398,150000,2022-04-28,2022-06-21,1600.0,45.00,35.00,2.0,129854.9000,0.865699
2499,20849,35913,384000,2023-02-09,2023-04-07,2915.0,55.00,53.00,1.7,289554.6500,0.754049