In [1]:
import os
import csv

import pandas as pd

# Load Data

In [2]:
# check shape of data

data_path = "data/Data"

for data in os.listdir(data_path):
    file = os.path.join(data_path, data)
    
    df = pd.read_csv(file)
    print(f"{data} shape: {df.shape}")

fasting.csv shape: (6189, 3)
harvests.csv shape: (8087, 9)
fastings.csv shape: (32379, 3)
mortalities.csv shape: (13221, 7)
samplings.csv shape: (15032, 7)
feeds.csv shape: (706908, 3)
cycles.csv shape: (2617, 24)
ponds.csv shape: (338, 10)
measurements.csv shape: (139050, 24)
farms.csv shape: (551, 4)
feed_tray.csv shape: (186664, 10)

In [3]:
# calculate sparse rate

for data in os.listdir(data_path):
    file = os.path.join(data_path, data)
    
    df = pd.read_csv(file)
    sparse_rate = (df.isna().sum().sum() / df.size) * 100
    print(f"{data} sparse rate: {sparse_rate:.2f} %")

fasting.csv sparse rate: 0.09 %
harvests.csv sparse rate: 2.82 %
fastings.csv sparse rate: 0.04 %
mortalities.csv sparse rate: 0.00 %
samplings.csv sparse rate: 13.01 %
feeds.csv sparse rate: 0.00 %
cycles.csv sparse rate: 7.93 %
ponds.csv sparse rate: 10.27 %
measurements.csv sparse rate: 62.54 %
farms.csv sparse rate: 7.49 %
feed_tray.csv sparse rate: 7.52 %

In [4]:
# see columns

for data in os.listdir(data_path):
    file = os.path.join(data_path, data)
    
    df = pd.read_csv(file)
    print(f"{data} columns: {df.columns}")

fasting.csv columns: Index(['logged_date', 'cycle_id', 'fasting'], dtype='object')
harvests.csv columns: Index(['cycle_id', 'updated_at', 'size', 'created_at', 'weight', 'id',
       'harvested_at', 'status', 'selling_price'],
      dtype='object')
fastings.csv columns: Index(['logged_date', 'cycle_id', 'fasting'], dtype='object')
mortalities.csv columns: Index(['id', 'cycle_id', 'quantity', 'recorded_at', 'created_at', 'updated_at',
       'average_weight'],
      dtype='object')
samplings.csv columns: Index(['cycle_id', 'updated_at', 'sampled_at', 'created_at', 'average_weight',
       'id', 'remark'],
      dtype='object')
feeds.csv columns: Index(['cycle_id', 'logged_at', 'quantity'], dtype='object')
cycles.csv columns: Index(['id', 'pond_id', 'species_id', 'total_seed', 'started_at',
       'finished_at', 'remark', 'created_at', 'updated_at', 'area',
       'initial_age', 'limit_weight_per_area', 'target_cultivation_day',
       'target_size', 'extracted_at', 'subscription_type', 'ordered_at',
       'hatchery_id', 'total_seed_type', 'hatchery_name', 'pond_name',
       'pond_length', 'pond_width', 'pond_depth'],
      dtype='object')
ponds.csv columns: Index(['id', 'farm_id', 'length', 'width', 'deep', 'created_at', 'updated_at',
       'record_id', 'extracted_at', 'max_seed_density'],
      dtype='object')
measurements.csv columns: Index(['pond_id', 'cycle_id', 'measured_date', 'morning_temperature',
       'evening_temperature', 'morning_do', 'evening_do', 'morning_salinity',
       'evening_salinity', 'morning_pH', 'evening_pH', 'transparency',
       'turbidity', 'ammonia', 'nitrate', 'nitrite', 'alkalinity', 'hardness',
       'calcium', 'magnesium', 'carbonate', 'bicarbonate', 'tom',
       'total_plankton_'],
      dtype='object')
farms.csv columns: Index(['id', 'province', 'regency', 'timezone'], dtype='object')
feed_tray.csv columns: Index(['id', 'logged_at', 'feed_logged_at', 'cycle_id', 'tray_number',
       'feed_remaining_percent', 'remark', 'created_at', 'updated_at',
       'local_feed_logged_at'],
      dtype='object')

In [5]:
# remove columns didn't exists in test document

drop_harvests_columns = ["updated_at", "created_at", "id"]
drop_mortalities_columns = ["updated_at", "created_at", "id"]
drop_samplings_columns = ["updated_at", "created_at", "id", "remark"]
drop_cycles_columns = [
    'remark', 
    'created_at', 
    'updated_at', 
    'initial_age', 
    'limit_weight_per_area', 
    'target_cultivation_day',
    'target_size', 
    'extracted_at', 
    'subscription_type', 
    'ordered_at',
    'hatchery_id', 
    'total_seed_type', 
    'hatchery_name', 
    'pond_name'
]
drop_measurements_columns = ['pond_id', 'turbidity']
drop_feed_trays_columns = ["id", "created_at", "updated_at", 'local_feed_logged_at']

## fasting or fastings?

In [6]:
# analyze fasting.csv and fastings.csv

fasting_file = os.path.join(data_path, "fastings.csv")
fasting_df = pd.read_csv(fasting_file)

fastings_file = os.path.join(data_path, "fasting.csv")
fastings_df = pd.read_csv(fastings_file)

display(fastings_df.head(10))
display(fasting_df.head(10))

  logged_date  cycle_id  fasting
0  2022-10-17     15804      1.0
1  2022-11-27     15804      0.0
2  2022-11-28     15804      0.0
3  2022-11-29     15804      0.0
4  2022-12-01     15804      1.0
5  2021-05-20     16250      1.0
6  2022-08-16     15487      0.0
7  2022-03-28     15106      1.0
8  2022-04-10     15106      1.0
9  2022-04-18     15106      1.0

  logged_date  cycle_id  fasting
0  2022-03-26   15013.0      1.0
1  2022-03-27   15013.0      0.0
2  2022-03-28   15013.0      0.0
3  2022-04-10   15013.0      1.0
4  2021-10-23   11848.0      1.0
5  2021-10-22   11848.0      1.0
6  2021-09-22   11848.0      1.0
7  2021-09-21   11848.0      1.0
8  2021-09-20   11848.0      1.0
9  2021-09-19   11848.0      1.0

In [7]:
# see one of the cycle id sample

display(fastings_df[fastings_df["cycle_id"] == 15804])
display(fasting_df[fasting_df["cycle_id"] == 15804])

  logged_date  cycle_id  fasting
0  2022-10-17     15804      1.0
1  2022-11-27     15804      0.0
2  2022-11-28     15804      0.0
3  2022-11-29     15804      0.0
4  2022-12-01     15804      1.0

      logged_date  cycle_id  fasting
26143  2022-07-24   15804.0      0.0
26144  2022-07-21   15804.0      0.0
26145  2022-07-22   15804.0      0.0
26146  2022-07-23   15804.0      0.0
26147  2022-07-20   15804.0      0.0
26148  2022-07-19   15804.0      0.0
26149  2022-07-18   15804.0      0.0
26150  2022-07-17   15804.0      0.0
26151  2022-07-16   15804.0      0.0
26152  2022-07-15   15804.0      0.0
26153  2022-07-25   15804.0      0.0
26154  2022-05-29   15804.0      1.0
26155  2022-05-30   15804.0      1.0
26156  2022-05-31   15804.0      1.0
26157  2022-06-01   15804.0      1.0
26158  2022-06-02   15804.0      1.0
26159  2022-06-03   15804.0      1.0
26160  2022-06-04   15804.0      1.0
26161  2022-06-05   15804.0      1.0
26162  2022-07-26   15804.0      1.0
26163  2022-07-27   15804.0      1.0

## Load All Files

In [8]:
os.listdir(data_path)

['fasting.csv',
 'harvests.csv',
 'fastings.csv',
 'mortalities.csv',
 'samplings.csv',
 'feeds.csv',
 'cycles.csv',
 'ponds.csv',
 'measurements.csv',
 'farms.csv',
 'feed_tray.csv']

In [9]:
df_cycles = pd.read_csv("data/Data/cycles.csv")
df_fastings = pd.read_csv("data/Data/fastings.csv")
df_fasting = pd.read_csv("data/Data/fasting.csv")
df_feed_trays = pd.read_csv("data/Data/feed_tray.csv")
df_feeds = pd.read_csv("data/Data/feeds.csv")
df_harvest = pd.read_csv("data/Data/harvests.csv")
df_measurements = pd.read_csv("data/Data/measurements.csv")
df_mortalities = pd.read_csv("data/Data/mortalities.csv")
df_samplings = pd.read_csv("data/Data/samplings.csv")

In [10]:
df_cycles = df_cycles.rename(columns={"id": "cycle_id"})

df_harvest = df_harvest.drop(columns=drop_harvests_columns)
df_mortalities = df_mortalities.drop(columns=drop_mortalities_columns)
df_samplings = df_samplings.drop(columns=drop_samplings_columns)
df_cycles = df_cycles.drop(columns=drop_cycles_columns)
df_measurements = df_measurements.drop(columns=drop_measurements_columns)
df_feed_trays = df_feed_trays.drop(columns=drop_feed_trays_columns)

df_fasting = pd.concat([df_fasting, df_fastings],axis=0)
df_fasting = df_fasting.drop_duplicates()

## combine data

In [11]:
list_df = {
    "df_cycles": df_cycles,
    "df_fasting": df_fasting,
    "df_feed_trays": df_feed_trays,
    "df_feeds": df_feeds,
    "df_harvest": df_harvest,
    "df_measurements": df_measurements,
    "df_mortalities": df_mortalities,
    "df_samplings": df_samplings
}

In [ ]:
# check dataframe shape

for name, df in list_df.items():
    print(f"{name} shape: {df.shape}")

df_cycles shape: (2617, 10)
df_fasting shape: (38108, 3)
df_feed_trays shape: (186664, 6)
df_feeds shape: (706908, 3)
df_harvest shape: (8087, 6)
df_measurements shape: (139050, 22)
df_mortalities shape: (13221, 4)
df_samplings shape: (15032, 3)

In [ ]:
# check unique of cycle id

for name, df in list_df.items():
    print(f"{name} cycle_id unique: {df['cycle_id'].nunique()}")

df_cycles cycle_id unique: 2500
df_fasting cycle_id unique: 1797
df_feed_trays cycle_id unique: 709
df_feeds cycle_id unique: 2500
df_harvest cycle_id unique: 2490
df_measurements cycle_id unique: 2500
df_mortalities cycle_id unique: 857
df_samplings cycle_id unique: 2307

In [16]:
# check if cycle id is only unique on df_cycle

id = set(df_cycles["cycle_id"].unique())

for name, df in list_df.items():
    if name == "df_cycles":
        continue
    else:
        cycle_id = set(df["cycle_id"].unique())
        print(f"{name} cycle_id unique: {cycle_id - id}")

df_fasting cycle_id unique: {np.float64(19048.0), np.float64(15068.0), np.float64(22404.0), np.float64(18653.0)}
df_feed_trays cycle_id unique: set()
df_feeds cycle_id unique: set()
df_harvest cycle_id unique: set()
df_measurements cycle_id unique: set()
df_mortalities cycle_id unique: set()
df_samplings cycle_id unique: set()